[editor]
bufferline = "multiple"
cursorline = true
end-of-line-diagnostics = "hint"
line-number = "relative"
rulers = [80]
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
character = "╎"
render = true

[editor.inline-diagnostics]
cursor-line = "error"
other-lines = "disable"

[editor.lsp]
auto-signature-help = false
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[keys.normal]
A-x = "extend_to_line_bounds"
X = "select_line_above"
esc = ["collapse_selection", "keep_primary_selection"]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]

[keys.select]
A-x = "extend_to_line_bounds"
X = "select_line_above"
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]

# [keys.normal."space"]
# "*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "global_search"]
# "f" = "file_picker_in_current_directory"
# "<" = "file_explorer_in_current_buffer_directory"
# "l" = ":sh git blame -L %{cursor_line},%{cursor_line} %{buffer_name}"
