- name: Configure Miscellaneous Ubuntu Settings and Installations
  hosts: localhost
  become: yes
  vars:
    typing_packages:
      - ibus-unikey
      - ibus-chewing
    input_sources:
      - "ibus/unikey"  # Vietnamese (Unikey)
      - "ibus/chewing" # Chinese (Chewing)
    kvm_packages:
      - qemu-kvm
      - qemu-utils
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - virt-manager
      - ovmf
      - qemu-guest-agent
      - spice-vdagent
      - samba
  tasks:
    - name: Install python3-psutil for dconf module
      apt:
        name: python3-psutil
        state: present
      become: yes

    - name: Enable click-to-minimize in GNOME Dash-to-Dock
      dconf:
        key: "/org/gnome/shell/extensions/dash-to-dock/click-action"
        value: "'minimize-or-previews'"
        state: present
      environment:
        XDG_RUNTIME_DIR: "{{ ansible_env.XDG_RUNTIME_DIR | default('/run/user/' ~ ansible_user_uid) }}"

    # Install Languages
    - name: Install typing packages with apt
      apt:
        name: "{{ typing_packages }}"
        state: present
        update_cache: yes
      become: yes

    - name: Configure GNOME input sources for typing
      shell: |
        gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us'), ('ibus', 'unikey'), ('ibus', 'chewing')]"
        ibus restart
      become: no
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ ansible_facts['user_uid'] }}"
        DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ ansible_facts['user_uid'] }}/bus"

    # Install Virtual-machine
    - name: Check if KVM is installed
      shell: kvm --version
      register: kvm_check
      ignore_errors: yes
      changed_when: false

    - name: Install KVM-related packages with apt (if nala unavailable)
      apt:
        name: "{{ kvm_packages }}"
        state: present
        update_cache: yes
      become: yes
      when: kvm_check.rc != 0

    - name: Check if NVIDIA drivers are installed
      command: nvidia-smi
      register: nvidia_check
      ignore_errors: yes
      changed_when: false

    - name: Install NVIDIA drivers if not present
      shell: |
        ubuntu-drivers devices
        ubuntu-drivers autoinstall
      when: nvidia_check.rc != 0  # Install only if nvidia-smi fails
      register: nvidia_install
      changed_when: nvidia_install.rc == 0
