- name: Configure Ubuntu and Install Flatpak Apps
  hosts: localhost
  become: yes  # Run tasks with sudo
  vars:
    essential_packages:
      # - curl
      # - git
      # - vim
      - build-essential
    flatpak_apps:
      - org.jousse.vincent.Pomodorolm
      - com.google.Chrome
      - md.obsidian.Obsidian
      - org.signal.Signal
      - com.obsproject.Studio
      - io.httpie.Httpie
      - org.libreoffice.LibreOffice
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes
      changed_when: false  # Avoid marking as changed

    - name: Upgrade all packages
      apt:
        upgrade: dist  # Equivalent to apt upgrade + apt dist-upgrade
        autoclean: yes
        autoremove: yes

    - name: Install essential packages
      apt:
        name: "{{ essential_packages }}"
        state: present

    - name: Install Flatpak
      apt:
        name: flatpak
        state: present

    - name: Add Flathub remote
      command: flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
      args:
        creates: ~/.local/share/flatpak/repo/flathub  # Skip if already added
      become: no  # Run as user, not sudo

    - name: Install Flatpak apps
      command: flatpak install --user -y {{ item }}
      loop: "{{ flatpak_apps }}"
      become: no  # Run as user
      register: install_result
      changed_when: "'already installed' not in install_result.stderr"

    - name: Uninstall Flatpak apps (optional)
      command: flatpak uninstall --user {{ item }}
      loop: "{{ flatpak_apps }}"
      become: no
      when: uninstall_flatpaks | default(false) | bool

