- name: Install Essential Development Packages
  hosts: localhost
  become: yes  # Needed for system-level operations
  vars:
    essential_packages:
      - nala
      - curl
      - git
      - vim
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
  tasks:
    - name: Install essential packages via apt
      apt:
        name: "{{ essential_packages }}"
        state: present
        update_cache: yes  # Ensure cache is fresh
      register: apt_install_result

    - name: Notify user of completion
      debug:
        msg: "Essential development packages installed successfully via nala."
      when: apt_install_result.changed
